import Toybox.Lang;

// Generated by tools/gen_tune_layouts.py from Refloat's settings.xml. Do not edit.

//! Where the tune fields (Tune, Tune Modifiers, ATR) sit in a Refloat config, per config
//! signature. Offsets count from the first byte after the signature.
module TuneLayouts {
    //! [config length, [offset, length, offset, length, ...]], or null for an unknown layout.
    function find(signature as Number) as [Number, Array<Number>] or Null {
        // 1.1-preview1
        if (signature == -1131654385) {
            return [260, [0, 16, 71, 12, 108, 71]];
        }
        // v1.0.0-beta2
        if (signature == 1306288156) {
            return [241, [0, 18, 69, 12, 106, 71]];
        }
        // v1.0.0-beta3, v1.0.0-beta4, v1.0.0-beta5
        if (signature == -564869041) {
            return [241, [0, 18, 69, 12, 106, 71]];
        }
        // v1.0.0-beta6, v1.0.0, v1.0.1-beta1, v1.0.1-beta2, v1.0.1-beta3, v1.0.1
        if (signature == -204169866) {
            return [240, [0, 16, 67, 12, 104, 71]];
        }
        // v1.1-preview2
        if (signature == 362983352) {
            return [266, [0, 16, 17, 10, 73, 12, 110, 71]];
        }
        // v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0, v1.1.1-beta1, v1.1.1-beta2, v1.1.1, v1.1.2
        if (signature == 15843867) {
            return [258, [0, 14, 60, 12, 97, 71]];
        }
        // v1.2.0-beta1
        if (signature == 611409867) {
            return [271, [0, 14, 62, 12, 99, 71]];
        }
        // v1.2.0-beta2
        if (signature == 740135323) {
            return [272, [0, 14, 63, 12, 100, 71]];
        }
        // v1.2.0-beta3, v1.2.0-beta4, v1.2.0, v1.2.1, v1.2.2-beta2, v1.2.2, v1.2.3
        if (signature == -1867011654) {
            return [272, [0, 14, 63, 12, 100, 71]];
        }
        // v1.2.2-beta1
        if (signature == -535111894) {
            return [270, [0, 14, 61, 12, 98, 71]];
        }
        // v1.3.0-beta1, v1.3.0-beta2, v1.3.0-beta3, v1.3.0
        if (signature == 421162011) {
            return [278, [0, 36, 83, 12, 117, 59]];
        }
        // v1.3.0-preview1
        if (signature == -702432228) {
            return [303, [0, 34, 87, 12, 124, 77]];
        }
        // v1.3.0-preview2
        if (signature == 154215301) {
            return [284, [0, 28, 79, 12, 115, 67]];
        }
        // v1.3.0-preview3
        if (signature == 1910207421) {
            return [284, [0, 28, 79, 12, 115, 67]];
        }
        return null;
    }

    //! Refloat releases each signature belongs to, for messages.
    function releases(signature as Number) as String? {
        if (signature == 421162011) { return "1.3.0-1.3.0-beta3"; }
        if (signature == 1910207421) { return "1.3.0-preview3"; }
        if (signature == 154215301) { return "1.3.0-preview2"; }
        if (signature == -702432228) { return "1.3.0-preview1"; }
        if (signature == -1867011654) { return "1.2.0-1.2.3"; }
        if (signature == -535111894) { return "1.2.2-beta1"; }
        if (signature == 740135323) { return "1.2.0-beta2"; }
        if (signature == 611409867) { return "1.2.0-beta1"; }
        if (signature == 15843867) { return "1.1.0-1.1.2"; }
        if (signature == 362983352) { return "1.1-preview2"; }
        if (signature == -204169866) { return "1.0.0-1.0.1-beta3"; }
        if (signature == -564869041) { return "1.0.0-beta3-1.0.0-beta5"; }
        if (signature == 1306288156) { return "1.0.0-beta2"; }
        if (signature == -1131654385) { return "1.1-preview1"; }
        return null;
    }
}
